version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "xxxxxxx-dev"
s3_bucket = "common-dev-sam-artifactstore"
s3_prefix = "xxxxxxx-dev"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = """\
    EnvironmentName=\"dev\" \
    AllowedClientOrigin=\"http://localhost:17329\" \
"""
tags = "project=\"xxxxxxx\" env=\"dev\" IaC=\"cfn\""
confirm_changeset = false

[prd]
[prd.deploy]
[prd.deploy.parameters]
stack_name = "xxxxxxx-prd"
s3_bucket = "common-prd-sam-artifactstore"
s3_prefix = "xxxxxxx-prd"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = """\
    EnvironmentName=\"prd\" \
    AllowedClientOrigin=\"https://\" \
"""
tags = "project=\"xxxxxxx\" env=\"prd\" IaC=\"cfn\""
confirm_changeset = false
