AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: xxxxxxx


Globals:
  Function:
    MemorySize: 128  # default
    Timeout: 13
    Layers:
      - !Ref ImportModulesLayer
      - !Ref UtilsLayer
    Environment:
      Variables:
        API_ALLOW_ORIGIN: !Sub ${ApiAllowOrigin}


Parameters:
  ResourcePrefix:
    Type: String
    Default: xxxxxxx
  EnvironmentName:
    Type: String
    AllowedValues:
      - dev
      - prd
  ApiAllowOrigin:
    Type: String


Resources:
  RestApis:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${ResourcePrefix}-${EnvironmentName}
      StageName: !Sub ${ResourcePrefix}-${EnvironmentName}-apis
      Cors:
        AllowOrigin: !Sub "'${ApiAllowOrigin}'"
        AllowHeaders: "'Content-Type, X-Amz-Date, X-Api-Key, Authorization, X-Amz-Security-Token'"
        AllowMethods: "'GET, POST, PUT, DELETE, OPTIONS'"

  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ResourcePrefix}-${EnvironmentName}-main
      CodeUri: ./functions/main
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      # Policies:
      #   - 
      Environment:
        # Variables:
        #   _NAME: !Sub ${}
      Events:
        RestApis:
          Type: Api
          Properties:
            RestApiId: !Ref RestApis
            Path: /main
            Method: get

  ImportModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: import modules containing PowerTools
      ContentUri: ./functions/layers/import_modules_layer
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9
  UtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: utils
      ContentUri: ./functions/layers/utils_layer
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9
